version: '3'

services:
    db:
        image: postgres:11-alpine
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_HOST_AUTH_METHOD="trust"
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
    app:
        build:
            context: .
        ports:
            - 80:8000
        volumes:
            - ./src:/app
        links:
            - db:db
        command:
                sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        environment:
            - DB_HOST=db
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - SECRET_KEY=${SECRET_KEY}
            - EMAIL_USER=${EMAIL_USER}
            - EMAIL_PASS=${EMAIL_PASS}
        depends_on: 
            - db
volumes:
    postgres_data: