# Generated by Django 3.2.3 on 2021-07-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
    ]
